import Foundation
@main struct StatsTests {
 @MainActor static func main() throws {
  var count=0
  func expect(_ good:Bool,_ description:String) { count+=1; if !good { fatalError(description) } }
  func data(_ s:String)->Data { Data(s.utf8) }
  let now=Date(timeIntervalSince1970:1000)
  var local=LocalMiningStats()
  local.engineStarted(offline:false,now:now)
  local.consume("miner speed 10s/60s/15m 525.5 522.0 n/a H/s",now:now)
  expect(local.currentRate(now:now)==525.5,"parse rate")
  expect(local.currentRate(now:now.addingTimeInterval(31))==nil,"stale local rate is unknown")
  local.consume("cpu accepted (1/0) diff 10000",now:now)
  local.consume("cpu rejected (1/1) stale",now:now)
  expect(local.accepted==1 && local.rejected==1 && local.lastAccepted==now,"share counters")
  local.engineStarted(offline:false,now:now)
  local.consume("cpu accepted (1/0)",now:now)
  expect(local.accepted==2,"thread restart keeps session counters")
  local.consume("net donate started",now:now); local.consume("cpu accepted (2/0)",now:now)
  expect(local.accepted==2,"donation shares excluded")
  local.consume("net donate finished",now:now); local.consume("cpu accepted (3/0)",now:now)
  expect(local.accepted==3,"shares resume after donation")
  local.engineStarted(offline:true,now:now); local.consume("cpu accepted (1/0)",now:now)
  expect(local.accepted==3,"benchmark does not earn shares")
  local.consume("miner speed 10s/60s/15m n/a n/a n/a H/s",now:now)
  expect(local.currentRate(now:now)==nil,"n/a not fabricated zero")
  local.engineStopped(now:now); expect(local.latestRate==nil,"stop clears rate")
  for n in 0..<500 { local.append(rate:100,now:now.addingTimeInterval(Double(n)*5)) }
  expect(local.history.count<=360,"graph history bounded")
  local.reset(now:now); expect(local.history.isEmpty && local.accepted==0,"session resets")
  let price=try PriceQuote.parse(data(#"{"data":{"amount":"68.246","base":"LTC","currency":"USD"}}"#),coin:"LTC",now:now)
  expect(price.usd==68.246 && price.isFresh(now:now),"price parser")
  expect(!price.isFresh(now:now.addingTimeInterval(600)),"price expires")
  expect((try? PriceQuote.parse(data(#"{"data":{"amount":"68","base":"BTC","currency":"USD"}}"#),coin:"LTC"))==nil,"wrong coin rejected")
  expect(StatsFormat.number("nan")==nil && StatsFormat.number(-1)==nil && StatsFormat.number(true)==nil,"invalid numeric fields rejected")
  expect(StatsFormat.usd(0.00018)=="<$0.01","tiny earnings visible")
  let address=data(#"{"success":true,"data":{"address":"fixture","uuid":"11111111-1111-1111-1111-111111111111","network":"LTC","balance_payable":"0.00000271","auto":false,"enabled":true,"err_flags":{"payment_error":false}}}"#)
  let stats=data(#"{"success":true,"data":{"coin":"LTC","network":"LTC","balance":"0.00000271","paid":"0","payment_threshold":"0.00075","rewarded":{"past_24h":"0.00000171"}}}"#)
  let workers=data(#"{"success":true,"data":{"randomx":{"workers":[{"name":"IdleMiner","online":true,"chr":"583"},{"name":"Other","online":true,"chr":"99999"}]}}}"#)
  let p=try PoolSnapshot.parse(addressData:address,statsData:stats,workersData:workers,coin:"LTC",now:now)
  expect(p.hasEarnings && p.paid==0 && p.balance==0.00000271,"pool balance earns but not paid")
  expect(abs(p.progress-0.361333333333)<0.00001,"threshold progress")
  expect(p.workerRate==583 && p.workerOnline==true,"only named worker counted")
  expect(p.automatic==false,"manual payout mode preserved")
  expect(p.rewards24h==0.00000171,"pool reward period")
  expect((try? PoolSnapshot.identifier(address,address:"different"))==nil,"wallet identity enforced")
  expect((try? PoolSnapshot.parse(addressData:address,statsData:data(#"{"success":false}"#),workersData:nil,coin:"LTC"))==nil,"API failure not zero balance")
  expect((try? PoolSnapshot.parse(addressData:address,statsData:stats,workersData:nil,coin:"BTC"))==nil,"wrong coin balance rejected")
  let service=StatsService(); service.configure(coin:"LTC",address:"fixture")
  service.pool=p; expect(!p.isFresh(),"old balance is stale")
  service.configure(coin:"BTC",address:"different"); expect(service.pool==nil && service.quote==nil,"wallet switch clears old earnings")
  let emptyStats=data(#"{"success":true,"data":{"coin":"LTC","network":"LTC","balance":"0","paid":"0","payment_threshold":"0.00075"}}"#)
  let empty=try PoolSnapshot.parse(addressData:address,statsData:emptyStats,workersData:nil,coin:"LTC")
  expect(!empty.hasEarnings,"zero balance and payouts are not earnings")
  let paidStats=data(#"{"success":true,"data":{"coin":"LTC","network":"LTC","balance":"0","paid":"0.001","payment_threshold":"0.00075"}}"#)
  let paid=try PoolSnapshot.parse(addressData:address,statsData:paidStats,workersData:nil,coin:"LTC")
  expect(paid.hasEarnings,"completed payouts count as earnings")
  local=LocalMiningStats(); local.engineStarted(offline:false,now:now)
  func health(requested:Bool=true,running:Bool=true,stopping:Bool=false,fatal:String?=nil,report:String?=nil,at:Date=now)->MiningHealth {
   MiningHealth.evaluate(requested:requested,running:running,stopping:stopping,fatalError:fatal,local:local,reportingIssue:report,now:at)
  }
  expect(health(requested:false,running:false).level == .inactive,"stopped is gray")
  expect(health(requested:false,report:"Price failed").level == .inactive,"paused overrides reporting error")
  expect(health().level == .inactive,"startup gray")
  expect(health(at:now.addingTimeInterval(181)).level == .issue,"startup timeout red")
  local.consume("miner speed 10s/60s/15m 530 n/a n/a H/s",now:now)
  expect(health().level == .inactive,"hashrate alone is not a confirmed pool connection")
  local.consume("net new job from rx.unmineable.com:443",now:now)
  expect(health().level == .working,"connected and hashing green without prior earnings")
  expect(health(stopping:true).level == .inactive,"thread transition gray")
  expect(health(fatal:"Engine exited").level == .issue,"fatal error red")
  expect(health(requested:false,running:false,fatal:"Engine exited").level == .issue,"unexpected engine exit remains red")
  expect(health(report:"Pool stats unavailable").level == .issue,"active reporting problem red")
  expect(health(at:now.addingTimeInterval(31)).level == .issue,"stalled rate red")
  local.consume("miner speed 10s/60s/15m 0 n/a n/a H/s",now:now.addingTimeInterval(31))
  expect(health(at:now.addingTimeInterval(31)).level == .issue,"zero hash updates do not hide a stall")
  local.consume("miner speed 10s/60s/15m 530 n/a n/a H/s",now:now)
  local.consume("net read error: end of file",now:now)
  expect(health().level == .issue,"disconnect red")
  local.consume("miner speed 10s/60s/15m 530 n/a n/a H/s",now:now)
  expect(health().level == .issue,"hash samples cannot clear connection error")
  local.consume("net new job from rx.unmineable.com:443",now:now)
  expect(health().level == .working,"recovery green")
  let credits=local.accepted; let rejected=local.rejected; let session=local.sessionStarted
  local.threadsChanged(now:now)
  expect(local.accepted==credits && local.rejected==rejected && local.sessionStarted==session,"thread reload preserves session credit")
  expect(local.poolConnected && local.connectionIssue==nil && local.currentRate(now:now)==nil,"thread reload keeps pool connection but clears old rate")
  local.consume("miner speed 10s/60s/15m 530 n/a n/a H/s",now:now)
  local.consume("net connect error: refused",now:now)
  expect(health(requested:false).level == .inactive,"pause overrides old connection issue")
  local.consume("cpu accepted (1/0)",now:now)
  local.consume("miner speed 10s/60s/15m 530 n/a n/a H/s",now:now)
  expect(health().level == .working,"accepted work confirms reconnection")
  local.engineStarted(offline:true,now:now)
  local.consume("miner speed 10s/60s/15m 800 n/a n/a H/s",now:now)
  expect(health().level == .working && health().message.contains("no earnings"),"benchmark green explicitly no earnings")
  local.engineStopped(now:now)
  expect(health(requested:false,running:false).level == .inactive,"stop clears active health")
  print("PASS: \(count) mining stats, price, balance, freshness, and mining health checks")
 }
}
